/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Spec version this build implements (mirrors `handshake::SPEC_VERSION`). */
export const SPEC_VERSION: string
/**
 * JCS-canonicalize a JSON document supplied as a UTF-8 string.
 *
 * We require pre-serialized JSON text rather than `napi::Unknown` so the FFI
 * surface is unambiguous and the Node caller sees the same behavior the
 * Python caller does. The TypeScript façade calls `JSON.stringify` first.
 */
export declare function canonicalize(jsonText: string): Buffer
/** Raw 32-byte SHA-256 digest of `data`. */
export declare function sha256(data: Buffer): Buffer
/** Lowercase-hex SHA-256 digest of `data`. */
export declare function sha256Hex(data: Buffer): string
/**
 * Plain object returned by `ed25519KeypairFromSeed`. NAPI-RS materializes
 * this as `{ seed: Buffer, publicKey: Buffer }` on the JS side.
 */
export interface Ed25519Keypair {
  seed: Buffer
  publicKey: Buffer
}
/**
 * Ed25519 keypair from a 32-byte seed (RFC 8032 §5.1.5). The seed is
 * round-tripped so callers don't need to hold the original buffer.
 */
export declare function ed25519KeypairFromSeed(seed: Buffer): Ed25519Keypair
/** Ed25519 sign — returns the raw 64-byte signature. */
export declare function ed25519Sign(seed: Buffer, message: Buffer): Buffer
/**
 * Ed25519 verify. Returns `true` on a valid signature, `false` otherwise.
 * Wrong-length keys / signatures throw (caller bug, not forgery).
 */
export declare function ed25519Verify(publicKey: Buffer, signature: Buffer, message: Buffer): boolean
/**
 * Plain object returned by `mldsa65KeypairFromSeed`. NAPI-RS materializes
 * this as `{ privateKey: Buffer, publicKey: Buffer }` on the JS side.
 */
export interface MlDsa65Keypair {
  privateKey: Buffer
  publicKey: Buffer
}
/** ML-DSA-65 (FIPS 204) keypair from a 32-byte seed. */
export declare function mldsa65KeypairFromSeed(seed: Buffer): MlDsa65Keypair
/**
 * ML-DSA-65 deterministic sign — returns the raw 3309-byte signature.
 *
 * We accept the seed (not the pre-derived private key) so the FFI surface is
 * uniform with the Ed25519 helpers and matches the Python and Go runners.
 * Determinism is enforced by the FIPS 204 §5.5 deterministic variant inside
 * `Keypair::sign`.
 */
export declare function mldsa65Sign(seed: Buffer, message: Buffer): Buffer
/**
 * ML-DSA-65 verify. Returns `true` on a valid signature, `false` otherwise.
 * Wrong-length keys / signatures throw (caller bug, not forgery).
 */
export declare function mldsa65Verify(publicKey: Buffer, signature: Buffer, message: Buffer): boolean
